language: python
python:
  - 2.7
  - 3.6

# Setup anaconda
install:
  - sudo apt-get install libhdf5-serial-dev gfortran gcc build-essential cmake libblas-dev liblapack-dev git
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      sudo apt-get install -y cmake make libboost-all-dev libxml2-dev libxml++2.6-dev libsqlite3-dev libhdf5-serial-dev libbz2-dev coinor-libcbc-dev coinor-libcoinutils-dev coinor-libosi-dev coinor-libclp-dev coinor-libcgl-dev libblas-dev liblapack-dev g++ libgoogle-perftools-dev python-dev python-tables python-pandas python-numpy python-nose python-jinja2 cython;
    else
      sudo apt-get install -y cmake make libboost-all-dev libxml2-dev libxml++2.6-dev libsqlite3-dev libhdf5-serial-dev libbz2-dev coinor-libcbc-dev coinor-libcoinutils-dev coinor-libosi-dev coinor-libclp-dev coinor-libcgl-dev libblas-dev liblapack-dev g++ libgoogle-perftools-dev python3-dev python3-tables python3-pandas python3-numpy python3-nose python3-jinja2 cython3;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda install -c anaconda jinja2 matplotlib scipy numpy cython pytest pandas h5py

  - git clone http://github.com/cyclus/cyclus
  - git clone http://github.com/cyclus/cycamore
  - python ./cyclus/install.py --core-version 9999.999
  - python ./cycamore/install.py

  - python ./setup.py install

# command to run tests
script:
  - pytest ./tests/continuous_integration_test.py