version: 2

jobs:

    build:
      docker:
        - image: nuclearbae/d3ploy
      working_directory: ~/d3ploy
      steps:
        - checkout
        - run:
            name: build d3ploy
            command: python setup.py install

    unit_test:
        docker:
            - image: nuclearbae/d3ploy
        working_directory: ~/d3ploy
        steps:
          - checkout
          - run:
                name: build
                command: |
                    python setup.py install
          - run:
                name: unit tests
                command: |
                    pytest ./tests/unit_tests/deploy_solver_unit_tests.py
    integration_test:
        docker:
            - image: nuclearbae/d3ploy
        working_directory: ~/d3ploy
        steps:
          - checkout
          - run:
                name: build
                command: |
                    python setup.py install
          - run:
                name: integration tests
                command: |
                    pytest ./tests/integration_tests/continuous_integration_test.py
                    pytest ./tests/integration_tests/constraint_test.py
                    pytest ./tests/integration_tests/tech_pref_test.py
    

workflows:
        version: 2
        build_and_test:
            jobs:
                - build
                - unit_test
                - integration_test